import { addTemplate, defineNuxtModule } from '@nuxt/kit'
import { toImports } from 'unimport'
import type { Import } from 'unimport'
import type { ESLintPluginData } from './utils'
import { Unimport } from './addons/unimport'

// Module options TypeScript interface definition
export interface ModuleOptions {
  /**
   * Enable unimport plugin that insert import statements automatically
   */
  unimport?: boolean

  /**
   * Enable TypeScript support
   */
  typescript?: boolean

  /**
   * Enable Vue support
   */
  vue?: boolean
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-module-eslint-config',
    configKey: 'eslintConfig',
  },
  defaults: {},
  setup(options, nuxt) {
    if (!nuxt.options.dev)
      return

    const addons: ESLintPluginData[] = []

    if (options.unimport)
      addons.push(Unimport(nuxt))

    addTemplate({
      filename: 'eslint.config.mjs',
      write: true,
      async getContents() {
        const importLines: Import[] = []
        const configLines: string[] = []

        for (const mod of addons) {
          importLines.push(...mod.imports)
          configLines.push(...mod.configLines)
        }

        return [
          '// ESLint config generated by Nuxt',
          toImports(importLines, false),
          `export default [`,
          ...configLines,
          `]`,
          '',
        ].join('\n')
      },
    })
  },
})
